apiVersion: v1
kind: Service
metadata:
  name: chat-app
  labels:
    app: chat-app
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
