apiVersion: v1
kind: Service
metadata:
  name: ecommerce-super-pets
  labels:
    app: ecommerce-super-pets
spec:
  type: NodePort
  selector:
    app: ecommerce-super-pets
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
