apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  labels:
    app: chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: chrisyp/sit727-72hd:v2
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: MONGO_HOSTS
          valueFrom:
            configMapKeyRef:
              name: chat-app
              key: MONGO_HOSTS
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: chat-app
              key: mongo-root-username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: chat-app
              key: mongo-root-password
        - name: MONGO_REPLICA_SET
          valueFrom:
            configMapKeyRef:
              name: chat-app
              key: MONGO_REPLICA_SET
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20